#pragma once

#define CFG_ENABLE_CAN 1
#define CFG_ENABLE_MOTORS 1
#define CFG_ENABLE_DISPLAY 1
#define CFG_ENABLE_WATCHDOG 1
#define CFG_ENABLE_RC 1
#define CFG_ENABLE_POWER_MONITOR 1
#define CFG_ENABLE_COMPANION 1
#define CFG_ENABLE_ONBOARD_COMPUTER 1

//#define CFG_START_WEB_SERVER_ON_STARTUP 0
#define CFG_DEBUG_LIST_TASKS 0

// Pins
#define CFG_RC_UART_TX 0
#define CFG_RC_UART_RX 1
#define CFG_COMPANION_UART_TX 2
#define CFG_COMPANION_UART_RX 3
#define CFG_ONBOARD_COMPUTER_UART_TX 4
#define CFG_ONBOARD_COMPUTER_UART_RX 5
