#pragma once

#define CFG_ENABLE_CAN 1
#define CFG_ENABLE_MOTORS 1
#define CFG_ENABLE_DISPLAY 0
#define CFG_ENABLE_WATCHDOG 0
#define CFG_ENABLE_RC 1
#define CFG_ENABLE_WEB_SERVER 0

#define CFG_START_WEB_SERVER_ON_STARTUP 0
#define CFG_DEBUG_LIST_TASKS 0

// Pins
#define CFG_RC_UART_TX 0
#define CFG_RC_UART_RX 1