# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MotorControl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EnableExtendedMode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EnableExtendedMode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEnableExtendedMode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EnableExtendedMode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def EnableExtendedModeStart(builder):
    builder.StartObject(0)

def Start(builder):
    EnableExtendedModeStart(builder)

def EnableExtendedModeEnd(builder):
    return builder.EndObject()

def End(builder):
    return EnableExtendedModeEnd(builder)


class EnableExtendedModeT(object):

    # EnableExtendedModeT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        enableExtendedMode = EnableExtendedMode()
        enableExtendedMode.Init(buf, pos)
        return cls.InitFromObj(enableExtendedMode)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, enableExtendedMode):
        x = EnableExtendedModeT()
        x._UnPack(enableExtendedMode)
        return x

    # EnableExtendedModeT
    def _UnPack(self, enableExtendedMode):
        if enableExtendedMode is None:
            return

    # EnableExtendedModeT
    def Pack(self, builder):
        EnableExtendedModeStart(builder)
        enableExtendedMode = EnableExtendedModeEnd(builder)
        return enableExtendedMode
