# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MotorControl

class EncoderCommands(object):
    NONE = 0
    EnableExtendedMode = 1
    StartMotor = 2
    StopMotor = 3
    TorqueControlMode = 4
    SpeedTorqueControlMode = 5
    PositionSpeedTorqueMode = 6
    SetMotorPositionToZero = 7
    MoveMotor = 8

def EncoderCommandsCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == EncoderCommands().EnableExtendedMode:
        import MotorControl.EnableExtendedMode
        return MotorControl.EnableExtendedMode.EnableExtendedModeT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == EncoderCommands().StartMotor:
        import MotorControl.StartMotor
        return MotorControl.StartMotor.StartMotorT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == EncoderCommands().StopMotor:
        import MotorControl.StopMotor
        return MotorControl.StopMotor.StopMotorT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == EncoderCommands().TorqueControlMode:
        import MotorControl.TorqueControlMode
        return MotorControl.TorqueControlMode.TorqueControlModeT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == EncoderCommands().SpeedTorqueControlMode:
        import MotorControl.SpeedTorqueControlMode
        return MotorControl.SpeedTorqueControlMode.SpeedTorqueControlModeT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == EncoderCommands().PositionSpeedTorqueMode:
        import MotorControl.PositionSpeedTorqueMode
        return MotorControl.PositionSpeedTorqueMode.PositionSpeedTorqueModeT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == EncoderCommands().SetMotorPositionToZero:
        import MotorControl.SetMotorPositionToZero
        return MotorControl.SetMotorPositionToZero.SetMotorPositionToZeroT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == EncoderCommands().MoveMotor:
        import MotorControl.MoveMotor
        return MotorControl.MoveMotor.MoveMotorT.InitFromBuf(table.Bytes, table.Pos)
    return None
