# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MotorControl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PositionSpeedTorqueMode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PositionSpeedTorqueMode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPositionSpeedTorqueMode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PositionSpeedTorqueMode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def PositionSpeedTorqueModeStart(builder):
    builder.StartObject(0)

def Start(builder):
    PositionSpeedTorqueModeStart(builder)

def PositionSpeedTorqueModeEnd(builder):
    return builder.EndObject()

def End(builder):
    return PositionSpeedTorqueModeEnd(builder)


class PositionSpeedTorqueModeT(object):

    # PositionSpeedTorqueModeT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        positionSpeedTorqueMode = PositionSpeedTorqueMode()
        positionSpeedTorqueMode.Init(buf, pos)
        return cls.InitFromObj(positionSpeedTorqueMode)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, positionSpeedTorqueMode):
        x = PositionSpeedTorqueModeT()
        x._UnPack(positionSpeedTorqueMode)
        return x

    # PositionSpeedTorqueModeT
    def _UnPack(self, positionSpeedTorqueMode):
        if positionSpeedTorqueMode is None:
            return

    # PositionSpeedTorqueModeT
    def Pack(self, builder):
        PositionSpeedTorqueModeStart(builder)
        positionSpeedTorqueMode = PositionSpeedTorqueModeEnd(builder)
        return positionSpeedTorqueMode
