# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MotorControl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetCurrentKp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetCurrentKp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetCurrentKp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetCurrentKp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetCurrentKp
    def Kp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SetCurrentKpStart(builder):
    builder.StartObject(1)

def Start(builder):
    SetCurrentKpStart(builder)

def SetCurrentKpAddKp(builder, kp):
    builder.PrependFloat32Slot(0, kp, 0.0)

def AddKp(builder, kp):
    SetCurrentKpAddKp(builder, kp)

def SetCurrentKpEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetCurrentKpEnd(builder)


class SetCurrentKpT(object):

    # SetCurrentKpT
    def __init__(self):
        self.kp = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        setCurrentKp = SetCurrentKp()
        setCurrentKp.Init(buf, pos)
        return cls.InitFromObj(setCurrentKp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, setCurrentKp):
        x = SetCurrentKpT()
        x._UnPack(setCurrentKp)
        return x

    # SetCurrentKpT
    def _UnPack(self, setCurrentKp):
        if setCurrentKp is None:
            return
        self.kp = setCurrentKp.Kp()

    # SetCurrentKpT
    def Pack(self, builder):
        SetCurrentKpStart(builder)
        SetCurrentKpAddKp(builder, self.kp)
        setCurrentKp = SetCurrentKpEnd(builder)
        return setCurrentKp
