# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MotorControl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetCurrentFilterGain(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetCurrentFilterGain()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetCurrentFilterGain(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetCurrentFilterGain
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetCurrentFilterGain
    def Gain(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SetCurrentFilterGainStart(builder):
    builder.StartObject(1)

def Start(builder):
    SetCurrentFilterGainStart(builder)

def SetCurrentFilterGainAddGain(builder, gain):
    builder.PrependFloat32Slot(0, gain, 0.0)

def AddGain(builder, gain):
    SetCurrentFilterGainAddGain(builder, gain)

def SetCurrentFilterGainEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetCurrentFilterGainEnd(builder)


class SetCurrentFilterGainT(object):

    # SetCurrentFilterGainT
    def __init__(self):
        self.gain = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        setCurrentFilterGain = SetCurrentFilterGain()
        setCurrentFilterGain.Init(buf, pos)
        return cls.InitFromObj(setCurrentFilterGain)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, setCurrentFilterGain):
        x = SetCurrentFilterGainT()
        x._UnPack(setCurrentFilterGain)
        return x

    # SetCurrentFilterGainT
    def _UnPack(self, setCurrentFilterGain):
        if setCurrentFilterGain is None:
            return
        self.gain = setCurrentFilterGain.Gain()

    # SetCurrentFilterGainT
    def Pack(self, builder):
        SetCurrentFilterGainStart(builder)
        SetCurrentFilterGainAddGain(builder, self.gain)
        setCurrentFilterGain = SetCurrentFilterGainEnd(builder)
        return setCurrentFilterGain
