# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MotorControl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetCurrentRef(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetCurrentRef()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetCurrentRef(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetCurrentRef
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetCurrentRef
    def CurrentRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SetCurrentRefStart(builder):
    builder.StartObject(1)

def Start(builder):
    SetCurrentRefStart(builder)

def SetCurrentRefAddCurrentRef(builder, currentRef):
    builder.PrependFloat32Slot(0, currentRef, 0.0)

def AddCurrentRef(builder, currentRef):
    SetCurrentRefAddCurrentRef(builder, currentRef)

def SetCurrentRefEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetCurrentRefEnd(builder)


class SetCurrentRefT(object):

    # SetCurrentRefT
    def __init__(self):
        self.currentRef = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        setCurrentRef = SetCurrentRef()
        setCurrentRef.Init(buf, pos)
        return cls.InitFromObj(setCurrentRef)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, setCurrentRef):
        x = SetCurrentRefT()
        x._UnPack(setCurrentRef)
        return x

    # SetCurrentRefT
    def _UnPack(self, setCurrentRef):
        if setCurrentRef is None:
            return
        self.currentRef = setCurrentRef.CurrentRef()

    # SetCurrentRefT
    def Pack(self, builder):
        SetCurrentRefStart(builder)
        SetCurrentRefAddCurrentRef(builder, self.currentRef)
        setCurrentRef = SetCurrentRefEnd(builder)
        return setCurrentRef
