# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MotorControl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetLimitSpeed(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetLimitSpeed()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetLimitSpeed(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetLimitSpeed
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetLimitSpeed
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SetLimitSpeedStart(builder):
    builder.StartObject(1)

def Start(builder):
    SetLimitSpeedStart(builder)

def SetLimitSpeedAddSpeed(builder, speed):
    builder.PrependFloat32Slot(0, speed, 0.0)

def AddSpeed(builder, speed):
    SetLimitSpeedAddSpeed(builder, speed)

def SetLimitSpeedEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetLimitSpeedEnd(builder)


class SetLimitSpeedT(object):

    # SetLimitSpeedT
    def __init__(self):
        self.speed = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        setLimitSpeed = SetLimitSpeed()
        setLimitSpeed.Init(buf, pos)
        return cls.InitFromObj(setLimitSpeed)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, setLimitSpeed):
        x = SetLimitSpeedT()
        x._UnPack(setLimitSpeed)
        return x

    # SetLimitSpeedT
    def _UnPack(self, setLimitSpeed):
        if setLimitSpeed is None:
            return
        self.speed = setLimitSpeed.Speed()

    # SetLimitSpeedT
    def Pack(self, builder):
        SetLimitSpeedStart(builder)
        SetLimitSpeedAddSpeed(builder, self.speed)
        setLimitSpeed = SetLimitSpeedEnd(builder)
        return setLimitSpeed
