# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MotorControl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetLimitCurrent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetLimitCurrent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetLimitCurrent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetLimitCurrent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetLimitCurrent
    def Current(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SetLimitCurrentStart(builder):
    builder.StartObject(1)

def Start(builder):
    SetLimitCurrentStart(builder)

def SetLimitCurrentAddCurrent(builder, current):
    builder.PrependFloat32Slot(0, current, 0.0)

def AddCurrent(builder, current):
    SetLimitCurrentAddCurrent(builder, current)

def SetLimitCurrentEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetLimitCurrentEnd(builder)


class SetLimitCurrentT(object):

    # SetLimitCurrentT
    def __init__(self):
        self.current = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        setLimitCurrent = SetLimitCurrent()
        setLimitCurrent.Init(buf, pos)
        return cls.InitFromObj(setLimitCurrent)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, setLimitCurrent):
        x = SetLimitCurrentT()
        x._UnPack(setLimitCurrent)
        return x

    # SetLimitCurrentT
    def _UnPack(self, setLimitCurrent):
        if setLimitCurrent is None:
            return
        self.current = setLimitCurrent.Current()

    # SetLimitCurrentT
    def Pack(self, builder):
        SetLimitCurrentStart(builder)
        SetLimitCurrentAddCurrent(builder, self.current)
        setLimitCurrent = SetLimitCurrentEnd(builder)
        return setLimitCurrent
