# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MotorControl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetPositionRef(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetPositionRef()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetPositionRef(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetPositionRef
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetPositionRef
    def PositionRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SetPositionRefStart(builder):
    builder.StartObject(1)

def Start(builder):
    SetPositionRefStart(builder)

def SetPositionRefAddPositionRef(builder, positionRef):
    builder.PrependFloat32Slot(0, positionRef, 0.0)

def AddPositionRef(builder, positionRef):
    SetPositionRefAddPositionRef(builder, positionRef)

def SetPositionRefEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetPositionRefEnd(builder)


class SetPositionRefT(object):

    # SetPositionRefT
    def __init__(self):
        self.positionRef = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        setPositionRef = SetPositionRef()
        setPositionRef.Init(buf, pos)
        return cls.InitFromObj(setPositionRef)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, setPositionRef):
        x = SetPositionRefT()
        x._UnPack(setPositionRef)
        return x

    # SetPositionRefT
    def _UnPack(self, setPositionRef):
        if setPositionRef is None:
            return
        self.positionRef = setPositionRef.PositionRef()

    # SetPositionRefT
    def Pack(self, builder):
        SetPositionRefStart(builder)
        SetPositionRefAddPositionRef(builder, self.positionRef)
        setPositionRef = SetPositionRefEnd(builder)
        return setPositionRef
