# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MotorControl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StartMotor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StartMotor()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStartMotor(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StartMotor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def StartMotorStart(builder):
    builder.StartObject(0)

def Start(builder):
    StartMotorStart(builder)

def StartMotorEnd(builder):
    return builder.EndObject()

def End(builder):
    return StartMotorEnd(builder)


class StartMotorT(object):

    # StartMotorT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        startMotor = StartMotor()
        startMotor.Init(buf, pos)
        return cls.InitFromObj(startMotor)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, startMotor):
        x = StartMotorT()
        x._UnPack(startMotor)
        return x

    # StartMotorT
    def _UnPack(self, startMotor):
        if startMotor is None:
            return

    # StartMotorT
    def Pack(self, builder):
        StartMotorStart(builder)
        startMotor = StartMotorEnd(builder)
        return startMotor
