# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MotorControl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StopMotor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StopMotor()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStopMotor(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StopMotor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def StopMotorStart(builder):
    builder.StartObject(0)

def Start(builder):
    StopMotorStart(builder)

def StopMotorEnd(builder):
    return builder.EndObject()

def End(builder):
    return StopMotorEnd(builder)


class StopMotorT(object):

    # StopMotorT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        stopMotor = StopMotor()
        stopMotor.Init(buf, pos)
        return cls.InitFromObj(stopMotor)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, stopMotor):
        x = StopMotorT()
        x._UnPack(stopMotor)
        return x

    # StopMotorT
    def _UnPack(self, stopMotor):
        if stopMotor is None:
            return

    # StopMotorT
    def Pack(self, builder):
        StopMotorStart(builder)
        stopMotor = StopMotorEnd(builder)
        return stopMotor
