# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MotorControl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TorqueControlMode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TorqueControlMode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTorqueControlMode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TorqueControlMode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def TorqueControlModeStart(builder):
    builder.StartObject(0)

def Start(builder):
    TorqueControlModeStart(builder)

def TorqueControlModeEnd(builder):
    return builder.EndObject()

def End(builder):
    return TorqueControlModeEnd(builder)


class TorqueControlModeT(object):

    # TorqueControlModeT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        torqueControlMode = TorqueControlMode()
        torqueControlMode.Init(buf, pos)
        return cls.InitFromObj(torqueControlMode)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, torqueControlMode):
        x = TorqueControlModeT()
        x._UnPack(torqueControlMode)
        return x

    # TorqueControlModeT
    def _UnPack(self, torqueControlMode):
        if torqueControlMode is None:
            return

    # TorqueControlModeT
    def Pack(self, builder):
        TorqueControlModeStart(builder)
        torqueControlMode = TorqueControlModeEnd(builder)
        return torqueControlMode
